# Run this one time to update a version 250116 database to a version 250124 database
# sqlite3 lociterm.db < thisfile.sql
.bail on

# Saving the scanner information in its own table too.

CREATE TABLE IF NOT EXISTS SCAN (
	GAME INTEGER NOT NULL PRIMARY KEY, 
	LASTSCAN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	STATUS INTEGER NOT NULL DEFAULT 2,
	FOREIGN KEY(GAME) REFERENCES GAMEDB(ID), 
	FOREIGN KEY(STATUS) REFERENCES GAMEDBSTATUS(ID) 
);

INSERT INTO SCAN ( GAME, LASTSCAN, STATUS )
SELECT ID AS GAME,
	COALESCE(LAST_MSSP, LAST_CONNECTION, CREATED) as LASTSCAN,
	(SELECT ID FROM GAMEDBSTATUS WHERE STATUS IS "Not Checked") AS STATUS
FROM GAMEDB
WHERE STATUS IS
	(SELECT ID FROM GAMEDBSTATUS WHERE STATUS IS "Approved")
;

# add the dbversion to the table.
INSERT INTO DBVERSION ("VERSION") VALUES ( 250124 );

.print DB updated to 250124.
